ys=0;
xn=[1,zeros(1,30)];
B=[2,0,-1];
A=[1,-0.7,0.1];
xi=filtic(B,A,ys);
yn=filter(B,A,xn,xi);
n=0:length(yn)-1;
subplot(2,1,1);
stem(n,yn,'.')
title('(a)');
xlabel('n');
ylabel('y(n)');
ys=0;
xn=[1,ones(1,30)];
B=[2,0,-1];
A=[1,-0.7,0.1];
xi=filtic(B,A,ys);
yn=filter(B,A,xn,xi);
n=0:length(yn)-1;
subplot(2,1,2);
stem(n,yn,'.')
title('(a)');
xlabel('n');
ylabel('h(n)');